### ISSUE TITLE
numpy import error

### ISSUE THREAD

**Issue by kmchord9** [kmchord9/raspi_realtime-matplot#2]
Traceback (most recent call last):
  File "/home/nmiri/.anyenv/envs/pyenv/versions/realtimeMatplot/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/nmiri/.anyenv/envs/pyenv/versions/realtimeMatplot/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/nmiri/.anyenv/envs/pyenv/versions/realtimeMatplot/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import numpy as np
  File "/home/nmiri/.anyenv/envs/pyenv/versions/realtimeMatplot/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/nmiri/.anyenv/envs/pyenv/versions/realtimeMatplot/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/home/nmiri/.anyenv/envs/pyenv/versions/realtimeMatplot/bin/python"
  * The NumPy version is: "1.19.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or director

**Comment by kmchord9** [comment]
https://qiita.com/hideki0145/items/298725f476d9164626ce
