### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kmchord9** [kmchord9/raspi_realtime-matplot#5]
python3 temp.py

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "temp.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/rcsetup.py", line 26, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/colors.py", line 82, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/scale.py", line 18, in <module>
    from matplotlib.ticker import (
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/ticker.py", line 179, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/pi/.local/lib/python3.7/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import

**Comment by kmchord9** [comment]
pip3 install numpy --upgrade

https://algorithm.joho.info/programming/python/numpy-core-multiarray-failed-to-import/

**Comment by kmchord9** [comment]
python3 temp.py
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "temp.py", line 3, in <module>
    import numpy as np
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/__init__.py", line 150, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/usr/bin/python3"
  * The NumPy version is: "1.21.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

**Comment by kmchord9** [comment]
sudo apt-get  install libatlas-base-dev

https://teratail.com/questions/293268

**Comment by kmchord9** [comment]
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

**Comment by kmchord9** [comment]
sudo apt-get install python3-gi-cairo
